import { useEffect, useState } from "react";

export type Language = "ru" | "uz";

const translations: Record<Language, Record<string, string>> = {
  ru: {},
  uz: {
    "Главная": "Bosh sahifa", "Товары": "Mahsulotlar", "Продажи": "Sotuvlar", "Склад": "Ombor", "Чеки": "Cheklar", "Клиенты": "Mijozlar", "Возвраты": "Qaytarishlar", "История склада": "Ombor tarixi", "Расходы": "Xarajatlar", "Поставщики": "Yetkazib beruvchilar", "Закупки": "Xaridlar", "Долги": "Qarzlar", "Категории": "Kategoriyalar", "Отчеты": "Hisobotlar", "Пользователи": "Foydalanuvchilar", "Журнал": "Jurnal", "Задачи": "Vazifalar", "Прочее": "Boshqa", "Выйти": "Chiqish", "Темная тема": "To'q mavzu", "Светлая тема": "Yorug' mavzu",
    "Категория": "Kategoriya", "Комментарий": "Izoh", "Ответственный": "Mas'ul", "Поиск по названию или SKU": "Nomi yoki SKU bo'yicha qidirish", "Добавить расход": "Xarajat qo'shish", "Поставщик": "Yetkazib beruvchi", "Выберите поставщика": "Yetkazib beruvchini tanlang", "Выберите закупку": "Xaridni tanlang", "Внести платеж": "To'lov kiritish", "Погасить долг": "Qarzni to'lash", "Активные": "Faol", "Погашенные": "To'langan", "Все": "Barchasi", "Выберите долг": "Qarzni tanlang", "Сумма платежа": "To'lov summasi", "Телефон": "Telefon", "Возникновение": "Yuzaga kelgan sana", "Статус": "Holat", "Чек": "Chek", "Выберите чек": "Chekni tanlang", "Количество": "Miqdor", "Причина": "Sabab", "Оформить возврат": "Qaytarishni rasmiylashtirish", "продано": "sotilgan", "Карта": "Karta", "Редактировать товар": "Mahsulotni tahrirlash",
    "Обзор": "Umumiy ko'rinish", "Продажи сегодня": "Bugungi sotuvlar", "Выручка сегодня": "Bugungi tushum", "Прибыль сегодня": "Bugungi foyda", "Активных товаров": "Faol mahsulotlar", "Клиентов": "Mijozlar", "Долги клиентов": "Mijozlar qarzi", "Долги поставщикам": "Yetkazib beruvchilar qarzi", "Денежный остаток": "Naqd qoldiq", "Продаж за месяц": "Oylik sotuvlar", "Расходы за месяц": "Oylik xarajatlar", "Выручка за месяц": "Oylik tushum", "Прибыль за месяц": "Oylik foyda", "Курс USD": "USD kursi", "Покупка": "Xarid", "Низкий остаток": "Kam qoldiq", "Последние продажи": "So'nggi sotuvlar", "Продажи за 7 дней": "7 kunlik sotuvlar",
    "Новая продажа": "Yangi sotuv", "Выберите товар": "Mahsulotni tanlang", "Корзина": "Savatcha", "Итого": "Jami", "Клиент": "Mijoz", "Без клиента": "Mijozsiz", "Способ оплаты": "To'lov usuli", "Наличные": "Naqd pul", "Банковская карта": "Bank kartasi", "Перевод": "O'tkazma", "Долг": "Qarz", "Смешанная оплата": "Aralash to'lov", "Срок погашения": "To'lash muddati", "Оформить продажу": "Sotuvni rasmiylashtirish", "Оформление...": "Rasmiylashtirilmoqda...", "Добавить": "Qo'shish", "Добавить клиента": "Mijoz qo'shish", "Новый клиент": "Yangi mijoz", "Имя": "Ism", "Адрес": "Manzil", "Сохранение...": "Saqlanmoqda...",
    "Вход в систему": "Tizimga kirish", "Управляйте магазином спокойно и точно.": "Do'konni qulay va aniq boshqaring.", "Пароль": "Parol", "Войти": "Kirish", "Ошибка запроса": "So'rov xatosi", "Загрузка...": "Yuklanmoqda...", "Нет данных": "Ma'lumot yo'q", "Добавлен": "Qo'shilgan", "Изменен": "O'zgartirilgan", "Дата": "Sana", "Действия": "Amallar",
    "Новая задача": "Yangi vazifa", "Название": "Nomi", "Описание": "Tavsif", "Добавить задачу": "Vazifa qo'shish", "Добавление...": "Qo'shilmoqda...", "Новые задачи": "Yangi vazifalar", "Сделано": "Bajarildi", "Выполнено": "Bajarildi", "Новых задач нет": "Yangi vazifalar yo'q", "Выполненных задач пока нет": "Bajarilgan vazifalar yo'q", "Добавил": "Qo'shdi", "Создано": "Yaratildi", "Сделал": "Bajardi", "Завершено": "Tugallandi",
    "Оплата": "To'lov", "Сумма": "Summa", "Прибыль": "Foyda", "Продаж за выбранный период нет": "Tanlangan davrda sotuvlar yo'q", "Продаж": "Sotuvlar", "Выручка": "Tushum", "Продано единиц": "Sotilgan birliklar", "Средний чек": "O'rtacha chek", "Себестоимость": "Tannarx", "Итоговая прибыль": "Yakuniy foyda", "Баланс периода": "Davr balansi", "Финансовый баланс": "Moliyaviy balans", "Денежные поступления": "Pul tushumlari", "Денежные расходы": "Pul xarajatlari", "Денежный баланс": "Pul balansi", "Логистика": "Logistika", "Профиль": "Profil", "Телефон не указан": "Telefon ko'rsatilmagan", "Текущая задолженность": "Joriy qarzdorlik", "Платежи": "To'lovlar", "Срок": "Muddat", "Выберите клиента, чтобы открыть профиль": "Profilni ochish uchun mijozni tanlang", "Удалить строку": "Qatorni o'chirish", "Добавить товар": "Mahsulot qo'shish", "Контактное лицо": "Aloqa shaxsi", "Добавить поставщика": "Yetkazib beruvchi qo'shish", "Оплата поставщику": "Yetkazib beruvchiga to'lov", "Закупка": "Xarid", "долг": "qarz", "Текущая неделя": "Joriy hafta", "Новая закупка": "Yangi xarid", "Сумма закупки": "Xarid summasi", "Логистика и разгрузка": "Logistika va tushirish", "Фактическая себестоимость": "Haqiqiy tannarx", "Оформить закупку": "Xaridni rasmiylashtirish", "Закупка оформлена": "Xarid rasmiylashtirildi", "Применить": "Qo'llash", "Сегодня": "Bugun", "30 дней": "30 kun", "Вчера": "Kecha", "Этот месяц": "Shu oy", "Прошлый месяц": "O'tgan oy", "От": "Dan", "До": "Gacha", "Все сотрудники": "Barcha xodimlar", "Все категории": "Barcha kategoriyalar", "Экспорт в Excel": "Excelga eksport", "Экспорт в PDF": "PDFga eksport", "Не удалось загрузить отчет": "Hisobotni yuklab bo'lmadi", "Дата начала не может быть позже даты окончания": "Boshlanish sanasi tugash sanasidan keyin bo'lishi mumkin emas"
  }
};

export function getLanguage(): Language { return localStorage.getItem("language") === "uz" ? "uz" : "ru"; }
export function setLanguage(language: Language) { localStorage.setItem("language", language); window.dispatchEvent(new CustomEvent("languagechange", { detail: language })); }
export function translate(key: string, language = getLanguage()) { return translations[language][key] || key; }
export function useLanguage() {
  const [language, setCurrentLanguage] = useState<Language>(getLanguage);
  useEffect(() => { const update = (event: Event) => setCurrentLanguage((event as CustomEvent<Language>).detail || getLanguage()); window.addEventListener("languagechange", update); return () => window.removeEventListener("languagechange", update); }, []);
  return { language, setLanguage, t: (key: string) => translate(key, language) };
}
